# sonar.projectKey=philippe-perrin-sonarsource_jquery
# sonar.organization=philippe-perrin-sonarsource
# sonar.host.url=https://dev11.sc-dev11.io/

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=jquery
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# sonar.sources=./src/ajax.js
#
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.scanner.skipSystemTruststore=true